### ISSUE TITLE
Deploy Smart Contract

### ISSUE THREAD

**Issue by gaboesquivel** [eoscostarica/eos-rate#104]

**Comment by danazkari** [comment]
Are we still planning on releasing to Jungle? I though we were going directly to Mainnet @gaboesquivel

**Comment by gaboesquivel** [comment]
Yes, I just renamed the issue.  

Mainnet only since this contract depends on data that is only available there.

**Comment by arturocr** [comment]
There's a contract already deployed, we are going to create another issue for handling rates updates in the future.
