### ISSUE TITLE
Configure staging server 

### ISSUE THREAD

**Issue by gaboesquivel** [eoscostarica/eos-rate#107]

**Comment by gaboesquivel** [comment]
I will host it heroku, it seems the simpler path https://docs.hasura.io/1.0/graphql/manual/deployment/heroku/index.html

**Comment by danazkari** [comment]
Do we have access to Google Cloud Platform? If so, I could take care of this and deploy it using kubernetes in case we have tons of success ;)

**Comment by gaboesquivel** [comment]
@danazkari great, thanks.
