### ISSUE TITLE
Submit Ratings with Scatter

### ISSUE THREAD

**Issue by gaboesquivel** [eoscostarica/eos-rate#108]
depends on #103

**Comment by gaboesquivel** [comment]
depends on #128

**Comment by arturocr** [comment]
@gaboesquivel @mahcr I'll be working on this, is there something that you worked on previously that I need to take in consideration?

**Comment by gaboesquivel** [comment]
please coordinate with @cristian-ramirez

**Comment by xavier506** [comment]
@arturocr  The contracts we are using are deployed on the jungle testnet https://jungle.bloks.io/account/eoseosrateio

You can call any action on that contract using the following endpoints

http://jungle2.cryptolions.io:80
https://jungle2.cryptolions.io:443
https://api.jungle.alohaeos.com:443
http://145.239.133.201:8888
http://jungle.eoscafeblock.com:8888
http://jungle.eosgen.io:80
https://jungle.eosn.io:443
https://eos-jungle.eosblocksmith.io:443
http://jungle.eosbcn.com:8080
https://jungle.eosmetal.io:443
http://jungle2-eos.blckchnd.com:8888
http://jungle.atticlab.net:8888
http://bp4-d3.eos42.io:8888
https://jungle.eosphere.io:443
http://213.202.230.42:8888
http://163.172.34.128:8888
http://jungle2.cryptolions.io:8888
http://jungle.eosamsterdam.net:80
https://jungle.eosusa.news:443
http://195.201.240.107:8888
http://88.12.21.79:8888
http://51.68.141.127:8988
http://85.214.253.244:8888

**Comment by gaboesquivel** [comment]
You can also use the eosinfra public proxy to connect to nearest/best api based on your location https://eosnode.tools/proxy
