### ISSUE TITLE
add 404 design

### ISSUE THREAD

**Issue by danazkari** [eoscostarica/eos-rate#111]
We need a design for `/not-found` pages.

![image](https://user-images.githubusercontent.com/349542/48980692-13084280-f092-11e8-92b0-4088ed920ec0.png)

**Comment by lelui12cr** [comment]
![image](https://user-images.githubusercontent.com/1937350/49635014-f9d19100-f9c3-11e8-9335-811b103b3063.png)
404 page done ready in zeplin: https://zpl.io/beLrOnW

**Comment by gaboesquivel** [comment]
done
