### ISSUE TITLE
Expand BP information

### ISSUE THREAD

**Issue by gaboesquivel** [eoscostarica/eos-rate#117]
We can include a column in hasura / postgress with an excerpt from block producers websites.

Other information may be userful also like for example:

Infrastructure:  ( link to resource where people can see data )
	- CPU Power
	- Uptime 
    - APIs

**Comment by JulianAlvarado** [comment]
@murillojorge @edgar-eoscostarica can we expand this benchmarking criteria from Business point of view and design?

We can extract more features from this criteria and create PBIs

**Comment by JulianAlvarado** [comment]
Necesitamos buscar o definir los texto que incluyen la descripcion del block producer.

**Comment by xavier506** [comment]
@tetogomez  
In a recent database migration we have included a new JSONB column `general_info` in the `producers` table. 

We can expand this JSON field to as many attributes as we want but I think for now we can begin with the  "From Their website:" 

```{
"websiteText" : "here goes text taken from the producer's website "
}```

This text would need to be manually added for each BP, so we would probably only offer it for the top 50 block producers that provide a website. This text  has lready been inlcuded in designs for the BP profile page so we can easily render it .

**Comment by xavier506** [comment]
I can create a JSON file with some seed data for top Block Producers such as:

```
{
	"bp":"eoscafeblock",
	"general_info" : {
		"websiteText" : "EOS Cafe Block is a leading block producer on the EOS blockchain focused on creating value through innovation, technology, and education. Our team is maximizing adoption of the world’s fastest blockchain by adding tangible value to the EOS ecosystem."
	}
},
{
	"bp":"costaricaeos",
	"general_info" : {
		"websiteText" : "We envision a community fostered by democratic values, that promotes an environment of innovation, responsible growth, and prosperity. Our goal is to build a strong EOS ecosystem to promote a culture that encourages learning and sharing of knowledge among people. Also, we are strong believers that technology facilitates collaborating and connecting ideas."
	}
}
```
