### ISSUE TITLE
Rating Categories Discussion

### ISSUE THREAD

**Issue by gaboesquivel** [eoscostarica/eos-rate#121]
Our current design has the follow 5 categories:

- Infrastructure.
- TestNets.
- Community.
- Transparency.
- Tooling

We posted this article to gather feedback from the community
https://medium.com/eos-costa-rica/eos-rate-block-producer-rating-system-efd586614695

This is summary of the feedback we've received form the token holders so far

- Many people have told us the current categories are fine.
- There are different user personas: proxies & bps / regular users.
- Idea: divide ratings in technical and non technical. 
- Infrastructure is measurable.
- Add more information about what are you rating.
- Add more more statistical data / metrics on the BP profile for people.  
- Other Categories:
  - Communication.
  - Integrity.
  - Development.
  - Education.
  - Add-Value Dapps. 
  - Technical Expertise.
  - APIs
  - Open Source

Please leave your comment with your preferred set of categories.
It can be 5 of more, and it can be divided in technical an non-technical, but not necessarily.

**Comment by gaboesquivel** [comment]
I like this set

- transparency
  - communication
  - ownership disclosure
  - financial disclosure
- integrity: 
  - follows statements on the regproducer contract
  - doesn't get involve in dishonest behavior
  - coherence to their public block producer pledge
- community:
   - user education
   - developer education
   - support
   - engagement
   - podcasts, blogs, video
   - meetups, hackathons and events
- development:
   - open source software
   - contributions to eosio software
   - contributions to governance model
   - add value dapps and services
- infrastructure:
   - mainnet resources
   - testnets
   - downtime
   - security
   - apis
   - cpu capacity
   - response time

**Comment by murillojorge** [comment]
I really like your set Gabo. It includes the previous categories in wider ones.

Regarding Integrity: I believe it would be useful to keep this category as Integrity/Trust because a user might be reluctant to determine the value of integrity if they don't completely know the BP, but they would know or at least suspect if they'd trust them or not, more easily.

Is integrity/trust actually trustworthiness?

**Comment by gaboesquivel** [comment]
I think they are synonyms. Personally I like integrity better, for me it emphasizes more on doing the right the thing when no-one is watching.  But that's my perception.

**Comment by murillojorge** [comment]
On our weekly call, we've come to the conclusion that trustiness is a better wording for integrity/trust.
Integrity is hard to rate and also might prove emotionally complex and even potentially conflictive.

**Comment by gaboesquivel** [comment]
Final decision was

```
- transparency
  - communication
  - ownership disclosure
  - financial disclosure
- trustiness: 
  - quality of being loyal or reliable
  - follows statements on the regproducer contract
  - doesn't get involve in dishonest behavior
  - coherence to their public block producer pledge
- community:
   - user education
   - developer education
   - support
   - engagement
   - podcasts, blogs, video
   - meetups, hackathons and events
- development:
   - open source software
   - contributions to eosio software
   - contributions to governance model
   - add value dapps and services, wallets
- infrastructure:
   - mainnet resources
   - second layer services ( explorers, apis, etc )
   - testnets
   - downtime
   - security
   - apis
   - cpu capacity
   - response time
```
