### ISSUE TITLE
Rate UI

### ISSUE THREAD

**Issue by gaboesquivel** [eoscostarica/eos-rate#128]
![rating-bps](https://user-images.githubusercontent.com/391270/49532881-24680080-f883-11e8-9161-1948ecb36f68.png)

**Comment by murillojorge** [comment]
We need to add a disable category element. Also a ? icon with a tooltip to provide more information on the category.

![desktop bp rating page - v1 0](https://user-images.githubusercontent.com/1179619/49674204-bbc18500-fa36-11e8-9569-501298355e26.png)

Refer to Zeplin page here: https://zpl.io/a7JovLj

**Comment by lelui12cr** [comment]
Done-UX

**Comment by arturocr** [comment]
This is done.
