### ISSUE TITLE
Main menu functionality

### ISSUE THREAD

**Issue by lelui12cr** [eoscostarica/eos-rate#134]
Mine propose its related to the header and the hide menu functionality

**Comment by lelui12cr** [comment]
following material design hide menu solutions

![desktop searchbar01 - v1 0](https://user-images.githubusercontent.com/1937350/49704906-9bccc580-fbde-11e8-9f9a-4dcdc0810c02.png)
![menu-hide_it](https://user-images.githubusercontent.com/1937350/49704907-9bccc580-fbde-11e8-8750-76c23a451b46.png)
![menu-hover_effect](https://user-images.githubusercontent.com/1937350/49704908-9bccc580-fbde-11e8-87b7-e05844da9440.png)

**Comment by murillojorge** [comment]
I like the idea of using icons on the menu elements. We need to make sure that all icons used are visually consistent.

I'm a bit hesitant of "over the content" sidebars if there's still enough space to show more than one card. Let's discuss it at the meeting.
