### ISSUE TITLE
Category rate disable element

### ISSUE THREAD

**Issue by murillojorge** [eoscostarica/eos-rate#135]
Users might be hesitant or unable to rate a specific category, so they need an element to disable the category in order to complete the BP rate.
Refer to Zeplin: https://zpl.io/a7JovLj
![desktop bp rating page - v1 0](https://user-images.githubusercontent.com/1179619/49768722-ec0d5b80-fca2-11e8-838b-13256d06a7c9.png)

**Comment by arturocr** [comment]
The toggles have been included.
