### ISSUE TITLE
Homepage menu opening as modal, and regular menu for rest of the app

### ISSUE THREAD

**Issue by danazkari** [eoscostarica/eos-rate#137]
Take material-ui.com as an example of the desired behavior

**Comment by lelui12cr** [comment]
![desktop-menu-v1 0](https://user-images.githubusercontent.com/1937350/50627517-5b204d80-0ef9-11e9-8d30-687ee65dd7bc.png)

**Comment by gaboesquivel** [comment]
can we close this @danazkari @lelui12cr ?

**Comment by arturocr** [comment]
This has been already fixed.
