### ISSUE TITLE
add beta to logo or somewhere in the site

### ISSUE THREAD

**Issue by gaboesquivel** [eoscostarica/eos-rate#140]
for the first version we want to have the word `beta` somewhere on the UI.

**Comment by lelui12cr** [comment]
![image](https://user-images.githubusercontent.com/1937350/52437133-bc7ca300-2adb-11e9-8ff7-e99d82fbbf0c.png)
Hello,

I have this tree proposals, following the market standard to add the 'beta' word in the logotype.
@gaboesquivel @danazkari @murillojorge @xavier506 

Please select one to add it for development

**Comment by gaboesquivel** [comment]
I like the third option

**Comment by edgar-eoscostarica** [comment]
I think the size is not proportional.  The beta should be more subtle in my opinion

**Comment by murillojorge** [comment]
Based on the original logo design using Lato fonts. 
Logo: https://zpl.io/2pM9G6y
Header: https://zpl.io/2pM9G6y

![eosrate-header-beta](https://user-images.githubusercontent.com/1179619/60141375-63ec3080-9772-11e9-8153-08092372524e.png)
