### ISSUE TITLE
Creation of Users Persona

### ISSUE THREAD

**Issue by lelui12cr** [eoscostarica/eos-rate#141]
To understand at least the fundamental characteristics and needs of your customer and make better design decisions, creating personas.

The creation following current analytics data. And then create the profiles.  As version one will not have interviews with real users, we will build proto-personas. In the next versions will be doing  real user interviews to finalize the user persona profile

**Comment by gaboesquivel** [comment]
We are starting the with proxies. We are going to validate the functionality with the first. Feel free to document the proxy persona.

The other persona is regular EOS token holder.

However I kinda feel this is overkill for this project. However, yes, I'm open to see your proposal.
