### ISSUE TITLE
Missing bp.json in block producer

### ISSUE THREAD

**Issue by danazkari** [eoscostarica/eos-rate#150]
Based on #148, we need a design to make sure our users know when a BP is offending the block producer contract.

**Comment by gaboesquivel** [comment]
We need to remove the chip from the main card and indicate that bp doesn't host a bpjson file in the profile page. We don't want to influence ratings, so we simply state that bp candidate doesn't host a valid bpjson in their profile page

**Comment by lelui12cr** [comment]
![tags](https://user-images.githubusercontent.com/1937350/52598948-dd673000-2e1c-11e9-89ec-9132f7888dc8.jpg)

As I talked with @danazkari We cannot use chips for this kind of interaction. I propose to use tags. The design changes a little from the sketch file so I took the card design directly from the live app.

**Comment by lelui12cr** [comment]
no go
