### ISSUE TITLE
Empty rating status for a new BP

### ISSUE THREAD

**Issue by danazkari** [eoscostarica/eos-rate#151]
We need an empty rating state for any new BP that doesn't have a rating yet.

**Comment by lelui12cr** [comment]
We can do a chip following the same idea of the case of 'no bp.json'

**Comment by gaboesquivel** [comment]
please paste attach design img from zeplin to understand what we are talking about 
https://scene.zeplin.io/project/5a58ea3341f76658994e000c

**Comment by arturocr** [comment]
The radars will put all points at the center when there are no ratings, that works for everyone.
