### ISSUE TITLE
Design: BPs with no BPJSON 

### ISSUE THREAD

**Issue by gaboesquivel** [eoscostarica/eos-rate#156]
Display the same page but instead of data, it should way this BP doesn't expose a valid bp.json. Use the same colors, no need to for red, we want to be impartial

Remove the Non-Compliante chip on the bp card.	

This is what we have.
![bp_profile](https://user-images.githubusercontent.com/391270/52524661-0775f200-2c65-11e9-885e-6080601008cd.png)

**Comment by gaboesquivel** [comment]
@lelui12cr please add a proposal for no bpjson. 
no red colors or alarming components, same colors.

**Comment by JulianAlvarado** [comment]
@murillojorge can you take a look please!

**Comment by xavier506** [comment]
@murillojorge 

Currently the app is not showing BPs with no BP.JSON 

@tetogomez We should make sure that all block producers are shown , even if they dont have `bp.json` files.

@murillojorge , If block producers dont have bp.json file we will not be able to find a logo for them. We should have a default image for block producers with no bp.json that could also serve the same purpose as the badge described in this ticket.
