### ISSUE TITLE
Upgrade front page

### ISSUE THREAD

**Issue by arturocr** [eoscostarica/eos-rate#166]
Let's upgrade the homepage following this design: https://scene.zeplin.io/project/5a58ea3341f76658994e000c/screen/5c05d7db60866701d3df1fb5

**Comment by arturocr** [comment]
@roafroaf will update the latest version of this.

**Comment by cristian-ramirez** [comment]
@roafroaf @murillojorge could you please update the description of the categories in the desigh and attach the icons for them

**Comment by arturocr** [comment]
@cristian-ramirez: @murillojorge is going to design the trustiness icon and he will also share some content for that section as well.

**Comment by murillojorge** [comment]
Trustiness missing icon: https://zpl.io/b6gN4RK
Homepage: https://zpl.io/agry6B9

@tetogomez
![Desktop Frontpage 3 Max-Width - v1 0](https://user-images.githubusercontent.com/1179619/61342308-08f4a900-a807-11e9-9104-af288c191083.png)

**Comment by murillojorge** [comment]
#173

**Comment by murillojorge** [comment]
Copy will be worked here: #173

**Comment by JulianAlvarado** [comment]
@arturocr @starlingnr can start this task today.

**Comment by arturocr** [comment]
> @arturocr @starlingnr can start this task today.

@JulianAlvarado that's great. Go ahead @starlingnr 😃

**Comment by murillojorge** [comment]
@tetogomez you can find the icon SVGs here:
https://app.zeplin.io/project/5a58ea3341f76658994e000c/styleguide/components?cseid=5d89301af71c2417ed36aa70
