### ISSUE TITLE
Account page design

### ISSUE THREAD

**Issue by arturocr** [eoscostarica/eos-rate#169]
Create a new design for the account page, that let us see the account details with some format.

**Comment by murillojorge** [comment]
https://zpl.io/amyL8em

![Desktop Account Page - v1 0](https://user-images.githubusercontent.com/1179619/61340219-9f709c80-a7fe-11e9-94c2-906785f90da7.png)

**Comment by arturocr** [comment]
According to the discussion we had on the weekly call of Sept. 10th 2019, we are leaving the activity section outside of the scope for now. It will be worked separately later on, probably when dfuse gets integrated (see #195).
