### ISSUE TITLE
Define color palette for radars

### ISSUE THREAD

**Issue by arturocr** [eoscostarica/eos-rate#170]

**Comment by murillojorge** [comment]
Let's give it a try with this color palette array:
["#366d7a", "#46a08a", "#7dc384", "#ffe6a7", "#fc8c71", "#fc2c44", "#a6541d", "#638123", "#15b71e", "#2975de", "#08a9e5", "#895ae7", "#e978b1", "#fa41c7", "#b195b0", "#9d1cf4"]

This is the main palette that I used to generate the array:
![Screen Shot 2019-08-13 at 7 31 02 PM](https://user-images.githubusercontent.com/1179619/62988280-0767d200-be01-11e9-8995-5ff1814acf65.png)
It was created with the help of this awesome tool:
http://vrl.cs.brown.edu/color

This is an example of a random set:
![eosrate-radar-02](https://user-images.githubusercontent.com/1179619/62988211-bd7eec00-be00-11e9-8b31-ecc35815194e.png)
