### ISSUE TITLE
Tweak global styles

### ISSUE THREAD

**Issue by arturocr** [eoscostarica/eos-rate#172]
Re-work  global color schemes and styles for the webapp.

![image](https://user-images.githubusercontent.com/5632966/72859289-dbdaf480-3c88-11ea-8c6f-a74a45b2ac23.png)

**Comment by xavier506** [comment]
@murillojorge  @tetogomez 

 I beleive these styles are located in a global JSON file for material UI.  Can we get a copy of the values we need to include in this json?

**Comment by xavier506** [comment]
@murillojorge  lets test out a light theme and see how that responds with users. 

This ticket covers all styles except for radar components which will be described in a different issue.

**Comment by xavier506** [comment]
la idea es modificar los valores de un archivo json para crear un light theme ,  seria bueno tener el input de @roafroaf  pero no necesariamente  lo tiene que hacer solo el , creo que @murillojorge nos puede ayudar tambien

**Comment by JulianAlvarado** [comment]
OK hablemos esto el lunes para coordinar un conversación entre ellos dos y terminar el entregable. @murillojorge @roafroaf coordinemos por slack!

**Comment by tetogomez** [comment]
this is our json theme

`const theme = createMuiTheme({
  typography: {
    useNextVariants: true
  },
  palette: {
    type: 'dark',
    background: {
      default: '#5b576f'
    },
    primary: {
      light: '#2b2e3e',
      main: '#010318',
      dark: '#000000',
      sectionBackground: '#1b1a2b',
      submenu: '#252838'
    },
    secondary: {
      light: '#fff',
      main: '#00c25b',
      dark: '#00902e'
    }
  },
  overrides: {
    root: {
      fontSize: '2em'
    },
    MuiSlider: {
      thumb: {
        backgroundColor: '#00c25b',
        '&$focused, &:hover': {
          boxShadow: '0px 0px 0px 9px rgba(0, 194, 91, 0.16)'
        },
        '&$activated': {
          boxShadow: '0px 0px 0px 18px rgba(0, 194, 91, 0.16)'
        }
      },
      trackBefore: {
        backgroundColor: '#00c25b'
      },
      trackAfter: {
        opacity: 0.8,
        backgroundColor: '#fff'
      }
    },
    MuiPaper: {
      root: {
        backgroundColor: '#1b1a2b'
      }
    },
    MuiListItem: {
      button: {
        color: 'white',
        '&:hover': {
          backgroundColor: '#5cf68a',
          color: 'black'
        }
      },
      root: {
        '&$selected': {
          color: 'black',
          backgroundColor: '#5cf68a'
        }
      }
    },
    MuiListItemText: {
      primary: {
        color: 'inherit'
      }
    },
    MuiSelect: {
      root: {
        paddingTop: 8
      }
    },
    MuiInput: {
      root: {
        height: 50,
        fontSize: 20
      }
    },
    MuiButton: {
      containedSecondary: {
        color: '#fff'
      }
    }
  }
})`

**Comment by xavier506** [comment]
Updated Color scheme by @roafroaf 
[EOSRATE-brandguide copy.pdf](https://github.com/eoscostarica/eos-rate/files/4166646/EOSRATE-brandguide.copy.pdf)

@murillojorge  can we use this to generate a matrial UI scheme?

**Comment by xavier506** [comment]
@roafroaf  there is a deploy preview for these changes in the following link https://5e5f138b26a95900086368ee--eosrate.netlify.com/

Please let us know your thoughts
