### ISSUE TITLE
Create copy content for homepage

### ISSUE THREAD

**Issue by arturocr** [eoscostarica/eos-rate#173]

**Comment by murillojorge** [comment]
Hey @edgar-eoscostarica we need copy for the new categories.
Use this as a visual guide: https://zpl.io/agry6B9
![Desktop Frontpage 3 Max-Width - v1 0](https://user-images.githubusercontent.com/1179619/61342465-799bc580-a807-11e9-87cd-e5eb1b94d096.png)

**Comment by JulianAlvarado** [comment]
Podemos usar un WBS (https://www.workbreakdownstructure.com/) para organizar el copy y con base a eso empezar a desarrollarlo.

**Comment by ldrojas** [comment]
[Texto EOS Rate homepage.docx](https://github.com/eoscostarica/eos-rate/files/3537746/Texto.EOS.Rate.homepage.docx)

Adjunto los textos para el homepage.

**Comment by JulianAlvarado** [comment]
@tetogomez aca estan los textos para que los podas validar!

**Comment by ldrojas** [comment]
_Hola, sugiero estos textos en español a los cuales les hice algunas correcciones pequeñas. Me avisan si tienen algún comentario!_

-

**#Califica fácilmente a productores de bloques EOS**

EOS Rate es una dApp de código abierto que permite a los titulares de tokens EOS calificar a los productores de bloques de manera rápida y sencilla.

Las calificaciones globales ayudan a capturar la opinión colectiva o "sabiduría de la multitud" y así medir si el sentimiento de los votantes se refleja en los patrones de votación.


**#Categorías de Calificación**

##Transparencia
Cumplimiento en términos de divulgación de propiedad, bp.json completo, uso de recompensas y situación financiera.

##Infraestructura
Estabilidad y confiabilidad de la infraestructura EOS.

##Confiabilidad
Colaboración y reputación entre la comunidad EOS.

##Comunidad
Creación de valor en la comunidad a través de educación y promoción de charlas, conversaciones, hackathons, conferencias, seminarios, espacios para desarrolladores y otros contenidos útiles.

##Desarrollo
Conocimientos técnicos y uso de software de código abierto, scripts, marcos, billeteras, portales de votación, métricas, etc.

Los titulares de tokens deberán firmar usando su billetera EOS para enviar su calificación, resultando en un proceso de votaciones más agnóstico y transparente. Una cuenta equivale a una calificación. Estas calificaciones son almacenadas de manera segura en la blockchain de EOS.


**#Democracia líquida**

Encuentra el productor de bloques que mejor te represente.

EOS Rate fue construido por una comunidad que valora la transparencia. La herramienta genera páginas de perfil de los productores de bloques y utiliza un componente radial único que llamamos "LEAF" (Factores de atributos de EOS líquidos) para comparar visualmente los atributos cualitativos más relevantes de los productores de bloques. Esto permite a los titulares de tokens votar de manera más informada.

**Comment by JulianAlvarado** [comment]
@kecoco16 can you proceed to update spanish i18n.
