### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by JulianAlvarado** [eoscostarica/eos-rate#182]
We need to make sure english/spanish version are updated and correct.

**Comment by royzumbado** [comment]
Working on it. Setting up the environment.

**Comment by royzumbado** [comment]
-Created a pull request with the changes.
-A request to make an additional change was made through the pull request, done and waiting approval to merge.
![image](https://user-images.githubusercontent.com/49529903/64480806-f2762880-d18b-11e9-8e5f-11fbdf697a82.png)
