### ISSUE TITLE
Cannot Rate Block Producers

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/eos-rate#209]
The Rate button has no effect

![image](https://user-images.githubusercontent.com/5632966/67980070-319c8500-fbe3-11e9-89a2-5db1ca153cce.png)

**Comment by JulianAlvarado** [comment]
@arturocr can you add your findings here; so @kriskoin can proceed.

**Comment by kriskoin** [comment]
@arturocr  this is list of the categories for the ratings json
  transparency
infrastructure
trustiness
development
community
