### ISSUE TITLE
BP info page is showing mock data

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/eos-rate#210]
![image](https://user-images.githubusercontent.com/5632966/67980870-ef744300-fbe4-11e9-9b3e-ab690b2e7e40.png)

**Comment by xavier506** [comment]
Info should come from each BPs bp.json file and from the ratings tables


https://jungle.bloks.io/account/eoseosrateio?nodeUrl=localhost%3A8888&systemDomain=eosio&loadContract=true&tab=Tables&account=eoseosrateio&scope=eoseosrateio&limit=100&table=stats

**Comment by murillojorge** [comment]
Please refer to this designs:
https://app.zeplin.io/project/5a58ea3341f76658994e000c/dashboard?seid=5e27a66566ed997dfe87a428
