### ISSUE TITLE
Add google analytics site metrics

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/eos-rate#214]
Lets analyze user traffic patterns and behaviour using google analytics.

**Comment by kriskoin** [comment]
@xavier506  @JulianAlvarado  There is a PR #219 to fix this issue

**Comment by xavier506** [comment]
@tetogomez assigning this issue to you for completion.

we can use [react-ga](https://github.com/react-ga/react-ga) to respect the react component's lifecycle. It will allows to track specific actions in different pages in the near future.
