### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by JulianAlvarado** [eoscostarica/eos-rate#215]
I as user I want to ability to control the language of my application from the UI

**Comment by murillojorge** [comment]
https://zpl.io/aR01R4z

![Desktop BPs Languages - v1 0](https://user-images.githubusercontent.com/1179619/70582860-8e477400-1b81-11ea-914e-1f9b3545d549.png)

**Comment by xavier506** [comment]
![image](https://user-images.githubusercontent.com/5632966/71943875-a366f100-3187-11ea-8c8d-7a3ae53e39af.png)

@tetogomez  this element is not placed correctly , it appears next to the footer and was designed to be near the header.

**Comment by xavier506** [comment]
Text field component has CSS classes that  have a conflict, @tetogomez agreed to swicth to a dopdown select component that will be styled the same way.

**Comment by kecoco16** [comment]
We can use [menu](https://material-ui.com/components/menus/#menus) to create this language selection component and this is the [task](https://github.com/eoscostarica/eos-rate/issues/223) for that
