### ISSUE TITLE
Cards and rate CTA buttons

### ISSUE THREAD

**Issue by murillojorge** [eoscostarica/eos-rate#216]
We need clearer and more easy to find RATE buttons.

**Comment by murillojorge** [comment]
Artboards here: https://zpl.io/VqlzxM6

![bocards-buttons](https://user-images.githubusercontent.com/1179619/68261205-fea02a00-0004-11ea-8d99-bbcffa8d0447.png)

**Comment by murillojorge** [comment]
Rate on BP page: https://zpl.io/b63K3gd

![ratabp](https://user-images.githubusercontent.com/1179619/68261393-a0277b80-0005-11ea-9927-ed54f03cfcd4.png)

**Comment by JulianAlvarado** [comment]
@adriexnet @tetogomez nos pueden dar un update de esta tarea aca para ir cerrando tickets!
