### ISSUE TITLE
Test contract on jungle testnet.

### ISSUE THREAD

**Issue by JulianAlvarado** [eoscostarica/eos-rate#217]
Test the contracts on jungle testnet for development readiness

**Comment by xavier506** [comment]
https://jungle.bloks.io/account/eoseosrateio?loadContract=true&tab=Actions&account=eoseosrateio&scope=eoseosrateio&limit=100&action=rateproducer&table=stats

**Comment by xavier506** [comment]
https://jungle.bloks.io/account/eoseosrateio
