### ISSUE TITLE
Production infrastructure  ( K8s )

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/eos-rate#224]
Production implementation of EOS Rate services (hasura+postgres, hapi, and react webapp) as containers and kubernetes deployments.

We will use CR servers openstack infrastructure for this task.

**Comment by xavier506** [comment]
@danazkari Do we still need this service for eosrate?

**Comment by xavier506** [comment]
Should we set up eosrate services on k8s / openstack?

**Comment by kuronosec** [comment]
TODO:
- [ ] #366
