### ISSUE TITLE
lodash vulnerability

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/eos-rate#229]
1 lodash vulnerability found in …/demux/yarn.lock on Jul 14, 2019
Remediation
Upgrade lodash to version 4.17.12 or later. For example:

lodash@^4.17.12:
  version "4.17.12"

**Comment by tetogomez** [comment]
same here, `lodash` package is not present into *…/demux/package.json*
please, check the comment here (https://github.com/eoscostarica/eos-rate/issues/230)

@xavier506
