### ISSUE TITLE
set-value vulnerability

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/eos-rate#230]
1 set-value vulnerability found in …/demux/yarn.lock on Oct 29, 2019
Remediation
Upgrade set-value to version 2.0.1 or later. For example:

set-value@^2.0.1:
  version "2.0.1"

**Comment by tetogomez** [comment]
`set-value` package is not present into *…/demux/package.json* as a dependency and yarn.lock is an autogenerate file and we shouldn't be able to modify.

@xavier506 I'm not sure if you want that I add `set-value` package in demux project or not

**Comment by xavier506** [comment]
we wont be using demux moving forward, i beleive this is a non-issue.
