### ISSUE TITLE
Staging Environment

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/eos-rate#242]
A staging environment  will be required for hosting the webapp and the backend services during development.  

An linux server will run the following services:

**Frontend:**

The web application will be available at both eosrate.io and 
staging.eosrate.io until a production ready instance of the application is ready.

**Backend:**

graphQL endpoint :
https://stage-graphql.eosrate.io/

**Comment by xavier506** [comment]
@danazkari  

I am seeing some errors regarding web socket conections to 

Request URL: wss://staging.eosrate.io/v1alpha1/graphql


`Error during WebSocket handshake: Unexpected response code: 404`

Have we considered web sockets in the staging environment setup?

**Comment by danazkari** [comment]
I've just uploaded a PR for fixing that, let's test it out and merge it if we can confirm it works. BTW, we need really need an SSL wildcard certificate.
