### ISSUE TITLE
No need to restrict voting to proxies

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/eos-rate#258]
If an account has voted for at least 21 block producers they can subit a rating. 

If an account votes for a proxy , the proxy must have voted for at least 21 bps.

https://github.com/eoscostarica/eos-rate/blob/1445a38a4187d15df062c62b1fc039e09abeac89/contracts/rateproducer/rateproducer.cpp#L77

**Comment by kriskoin** [comment]
the commit a0bf27e45e172a763248896a8e6f842c759eb218 fix this issue

**Comment by kriskoin** [comment]
final fix  commit : 9c323f5dff3a117b0b0b691f6ab28871a1ed15b9
