### ISSUE TITLE
Rename `proxy_voters_cntr` table column.

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/eos-rate#260]
Rename `proxy_voters_cntr` in `block_producers_stats` table to just  `voters_cntr` as we are no longer limiting voting to just proxies.

https://github.com/eoscostarica/eos-rate/blob/42dc09a26da16a863379e596912a0f72f7709e91/contracts/rateproducer/rateproducer.cpp#L249

Related to: Restrict Rating to accounts with more than 21 votes #237

**Comment by xavier506** [comment]
@kriskoin  what do you think about renaing this to  `ratrings_cntr` ?

**Comment by kriskoin** [comment]
@xavier506  sounds good, the commit c482f98d395f6e1856f26c3e53265eab5b974b2c fix this issue

**Comment by kriskoin** [comment]
final fix commit : 9c323f5dff3a117b0b0b691f6ab28871a1ed15b9
