### ISSUE TITLE
Smart Contract Unit Testing

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/eos-rate#267]
Review Smart Contract Testing Approach 

https://github.com/eoscostarica/eos-rate/blob/083797a304e0b44db0452602092a5b9eac56f6e7/contracts/tests/test.js#L27

**Comment by xavier506** [comment]
@kriskoin Please privide the bash scripts you are using to test the contracts.

**Comment by kriskoin** [comment]
@xavier506  i figured out was the problem, and i fix it
theres a PR #270 which include those scripts

**Comment by kriskoin** [comment]
PR #270
