### ISSUE TITLE
Video overlapping text on responsive view

### ISSUE THREAD

**Issue by JulianAlvarado** [eoscostarica/eos-rate#278]
El video a la par del text esta overlapping el texto en Macbook pro 13 view.

<img width="1244" alt="Screen Shot 2020-02-05 at 8 59 36 AM" src="https://user-images.githubusercontent.com/18537303/73853171-0f279280-47f6-11ea-94cf-da66c654e259.png">

**Comment by murillojorge** [comment]
This fix is done and comes out with the new light theme.

**Comment by murillojorge** [comment]
We should explore leaving the audio and record the screen while using the app.
