### ISSUE TITLE
Voting Portal

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/eos-rate#281]
As a eosrate user I should be able to vote for my favorite block producers.

**Comment by murillojorge** [comment]
As discussed with @xavier506 we can utilize the compare tool as a way to vote for BPs. I'll proceed to create a prototype to test the idea first.

**Comment by xavier506** [comment]
@murillojorge  I think we can rename the Compare Tool to Voting Portal and use the same functionality to "build my vote"

**Comment by xavier506** [comment]
Developer Docs Reference

https://developers.eos.io/manuals/eos/latest/cleos/command-reference/system/system-voteproducer-prods

**Comment by murillojorge** [comment]
A voting tool that does not contain any BP radars must appear collapsed.

**Comment by murillojorge** [comment]
I have one suggestion. I think if the voting tool does not contain any BPs it should collapse only appearing visible if one or more BPs are added to it.

@tetogomez @xavier506
