### ISSUE TITLE
User comments section

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/eos-rate#282]
As a rater I can leave comments on block producers so that more information is available around ratings.

**Comment by xavier506** [comment]
@adriexnet  @leisterfrancisco 

I wonder if exploring the Context Free data option of nodeos would be useful for this feature.


https://developers.eos.io/manuals/eos/v2.0/nodeos/concepts/context-free-data/index

**Comment by murillojorge** [comment]
People might change their minds, specially when commenting on other people or entities. Deleting comments is a feature that’s desirable from a UX standpoint, for sure.
