### ISSUE TITLE
Create automated deployment script

### ISSUE THREAD

**Issue by danazkari** [eoscostarica/eos-rate#286]
As a developer, I want to be able to deploy the code by merging PRs to staging

**Comment by xavier506** [comment]
@danazkari  can you provide an update for this task? 

perhaps @kuronosec  can help us with this task?

**Comment by kuronosec** [comment]
@xavier506 @danazkari yes sure. If we are not longer using netifly, are we going to use a k8s cluster right? Do we have a CI tool already?
