### ISSUE TITLE
Clear ratings for inactive producers

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/eos-rate#300]
There should be a periodic check to optimize the ratings table where ratings for inactive block producers get cleared in order to save RAM.

For example: 

`eoscrprodo55` and `eoscrprodo11` are no longer registered block producers however their ratings remain in the table. These should be cleaned out to reflect only registred block producers

![image](https://user-images.githubusercontent.com/5632966/74621830-1018c800-5104-11ea-8474-9bcfb2145f3a.png)

**Comment by kriskoin** [comment]
Done!!
in order to clean data you can call the erase action 
```cleos -u http://monitor.jungletestnet.io:8888 push action rateproducer erase '{"bp_name":"eoscrprodo55"}' -p rateproducer@active```

**Comment by xavier506** [comment]
@kriskoin  what happens when a BP is actuv , then becomes inactive ? should it remain in the table unless it is deleted automatically?


this happens when we run unit tests producers are registered and then unrgistered but the ratings remain in the table.

**Comment by kriskoin** [comment]
@xavier506  after an un-registration , the vote remain in the table, we need something to trigger the erase action after a un-registration

**Comment by xavier506** [comment]
@kriskoin  maybe we can use something like https://croneos.io/ to periodically check for inactive BPs and remove them from the blockchain tables. This will help save RAM
