### ISSUE TITLE
Average and number of ratings on card

### ISSUE THREAD

**Issue by murillojorge** [eoscostarica/eos-rate#302]
As a user I'd like to see how many ratings and what's the average of each BP on cards and/or radars, so I can inform myself faster.

**Comment by xavier506** [comment]
@murillojorge  are you ferring to having this info on the rating view? The info is already showing on the BP card. 

@tetogomez I do think we need to format the average ratings to be 2 decimals.


![image](https://user-images.githubusercontent.com/5632966/76220510-3995b280-61dd-11ea-8e4c-cedf1ca6bd67.png)

**Comment by tetogomez** [comment]
@murillojorge  we merge some changes in order to show these values (average & rate) on the BP card header

**Comment by murillojorge** [comment]
Sorry. Closed this by mistake.

**Comment by murillojorge** [comment]
@tetogomez could you please adapt the text like this component? 
https://zpl.io/bzoowq7
