### ISSUE TITLE
Sort and Filter Block Producers

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/eos-rate#346]
As a user I would like to sort block producers according to the followimg parameters:

- Top Ratings General 
- Top Ratings Infrastructure
- Top Ratings Community
- Top Ratings Trustiness
- Top Ratings Development
- Top Ratings Transparency  

- Votes / Rewards per day
-

**Comment by murillojorge** [comment]
We have a lot of real state on the menu, I think we can use it to filter too. What do you guys think?
https://zpl.io/bzodd5l
![Desktop BPs Top Filters](https://user-images.githubusercontent.com/1179619/78087335-04b0f180-737e-11ea-9fd3-eeb9f4bb4f68.png)
