### ISSUE TITLE
Review TokenPocket integration

### ISSUE THREAD

**Issue by edgarithm** [eoscostarica/eos-rate#350]
User is unable to login using the TokenPocket mobile wallet

**Comment by edgar-eoscostarica** [comment]
https://files.slack.com/files-pri/T27SJUYVA-F0107H46RHT/download/file_from_ios.mp4

**Comment by tetogomez** [comment]
Hi guys, I spent my day working on solve this bug, but I couldn't find any issues related to the token pocket authenticator.
But I found this:

> ### Using Token Pocket within your app is no different than using other authenticator plugins. However, if your application is being used from within the Token Pocket mobile app it is using an embedded browser to view the application. The main restriction is that the Token Pocket mobile app (and consequently the authenticator) can ONLY communicate with EOS Mainnet. So when setting up UAL, if you specify other chains it will not work. This is also true if you specify additional chains along with Mainnet. This can make testing difficult if your application is using contracts that are not yet deployed to Mainnet.

I'm not sure if @xavier506 can test the EOS RATE web app using MAINNET, please let me know.

CC: @edgar-eoscostarica
