### ISSUE TITLE
Incosistent HTTPS requests error

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/eos-rate#359]
SSL error due to incosistent use of protocol. All `http://` links must be replaced with `https://`
![image](https://user-images.githubusercontent.com/5632966/77275269-81a4e280-6c7d-11ea-8090-a5b7050cc749.png)

**Comment by tetogomez** [comment]
Most of the HTTP that we are using is for SVG files if we change it to use HTTPS we break all of this:
![image](https://user-images.githubusercontent.com/10634375/77563546-0878db80-6e87-11ea-88f2-c38a9739f664.png)

I'm not sure if @murillojorge can help me with that?

CC: @xavier506

**Comment by xavier506** [comment]
@tetogomez  where  are the SVG files hosted? 

please share the URL for these images

**Comment by tetogomez** [comment]
@xavier506  We have the SVG files into the FE project (`src/components/icon/${SVG-FILE}`)
but the problem is the URL into the SVG file
 
![image](https://user-images.githubusercontent.com/10634375/78624605-45f64500-7847-11ea-8d45-a87c4e097a2a.png)
