### ISSUE TITLE
Deploy contracts to mainnet

### ISSUE THREAD

**Issue by murillojorge** [eoscostarica/eos-rate#361]

**Comment by kriskoin** [comment]
Error 3080001: Account using more than allotted RAM usage
Error Details:
account rateproducer has insufficient ram; needs 325260 bytes has 5378 bytes

@xavier506  Could you put more resources for rateproducer account

**Comment by xavier506** [comment]
@kriskoin  we have allocated more ram to the account , please try again.

**Comment by kriskoin** [comment]
@xavier506 , @edgar-eoscostarica so sorry i made wrong math with the ram cost
now i get the error
Error Details:
account rateproducer has insufficient ram; needs 325260 bytes has 98126 bytes
looks we need around 17.6 EOS to alllocate the smart contract
98126-5378 = 92748 for 5 extra EOS
325260 (contract size) / 92748 (5 EOS) = 3.50 *5=17.54
we need at least 13 EOS extra

**Comment by xavier506** [comment]
RAM increased to 459.62 KB
https://bloks.io/transaction/1dcb6e9891b05cafd51b3ff3d4d57c6359824070f685377d6df377d02d790cf1

**Comment by kriskoin** [comment]
@xavier506  could you buy CPU time please

billed CPU time (983 us) is greater than the maximum billable CPU time for the transaction (22 us)

**Comment by kriskoin** [comment]
the contract was published on the mainnet, successfully
