### ISSUE TITLE
Define and explain the branches usage and create tags for stable versions

### ISSUE THREAD

**Issue by kuronosec** [eoscostarica/eos-rate#393]
We should explain better for newcomers what are the different branches usage (CONTRIBUTING.md), define what the production branch is (I think its mixed among master and staging) and define a versioning scheme to create stable tags.

**Comment by xavier506** [comment]
@kuronosec  I think this is a great idea

#### `master` branch : ####
- is hosted on k8s 
- should be configured via env vars to point to the EOS mainnet endpoint:  https://api.eosargentina.io/
- domain: https://eosrate.io

#### `staging` branch : ####
- is hosted on ubuntu server 
- should be configured via env vars to point to the JUNGLE testnet endpoint:  https://jungle.eosio.cr
- domain: https://staging.eosrate.io

@tetogomez can help us with the following tasks:

- Merge staging into master
- Document Branching strategy
- Create v1 tag

**Comment by xavier506** [comment]
As far as developer guidelines we had started this a while back 

https://developers.eoscostarica.io/docs/open-source-guidelines

@JulianAlvarado  I think it may be a good time to. revisit the developer guidelines, uoodate them and make sure they are available on all open source projects. 

@JustinCast  can help us with publihing any content.
