### ISSUE TITLE
Single BP Page Design

### ISSUE THREAD

**Issue by murillojorge** [eoscostarica/eos-rate#40]
We need a page to see a specific block producer information and graph.

**Comment by murillojorge** [comment]
I've uploaded a design prototype in order to decide what information will be displayer for specific BPs.
Check it out here:
https://app.zeplin.io/project/5a58ea3341f76658994e000c/screen/5bb6aa7f48a15c645a7a1ffe

Also take a look at the new footer!

**Comment by gaboesquivel** [comment]
the project link is not public @murillojorge

**Comment by murillojorge** [comment]
I'll just start uploading the prototypes.
![desktop bp page footer](https://user-images.githubusercontent.com/1179619/47379140-4b91b680-d6b7-11e8-82c5-21c452853299.png)

**Comment by gaboesquivel** [comment]
done
