### ISSUE TITLE
Update Hasura Version 

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/eos-rate#408]
### Update to Beta 4 version 

`hasura/graphql-engine:v1.2.0-beta.4.cli-migrations`

How do we update the hasura version in k8s?

There may be backwards compatibility issues with 1.20 , please investigate

**Comment by xavier506** [comment]
https://github.com/xavier506/eos-rate/tree/update-hasura

**Comment by kuronosec** [comment]
You just have to modify kubernetes/hasura-deployment.yaml. It does not seem to generate problems.
