### ISSUE TITLE
Compare tool

### ISSUE THREAD

**Issue by murillojorge** [eoscostarica/eos-rate#41]
This is the prototype for the compare tool for BPs.

https://scene.zeplin.io/project/5a58ea3341f76658994e000c/screen/5bbbc5e4eb1a041924c1ec5e

**Comment by murillojorge** [comment]
Another prototype can be found here:

https://scene.zeplin.io/project/5a58ea3341f76658994e000c/screen/5bbbd3d76bc6d61900b75a0f

**Comment by murillojorge** [comment]
![desktop bps compare hi-fi proto](https://user-images.githubusercontent.com/1179619/47379324-cd81df80-d6b7-11e8-97fb-da57ed8a8970.png)

**Comment by murillojorge** [comment]
Another option, with uncollapsed graphs.
![desktop bps compare 2 hi-fi proto](https://user-images.githubusercontent.com/1179619/47379380-fbffba80-d6b7-11e8-9ee5-21dae24e67e9.png)

**Comment by gaboesquivel** [comment]
done
