### ISSUE TITLE
Allow users to clear ratings and recover RAM

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/eos-rate#431]
Users can update ratings but they cannot clear them completely.  Users may want to recover their ram and delete their ratings. @kriskoin  I think we can create a smart contract action for this and add the option in the user profile section.

![image](https://user-images.githubusercontent.com/5632966/82379274-dcd82480-99e3-11ea-90cd-d193d47e2919.png)

**Comment by Soleone** [comment]
Please, and thank you! This is a good way to lead by example, not enough smart contracts make this easy enough.

**Comment by kriskoin** [comment]
Hi theres a PR #443  which include a new action within contract  for the new feature requested
