### ISSUE TITLE
 install the RapidSSL intermediate Certificate

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/eos-rate#433]
I got the following unexpected response when trying to retrieve <https://eosrate.io/>:

`500 Can't connect to eosrate.io:443 (certificate verify failed)`

https://validator.w3.org/check?uri=https%3A%2F%2Feosrate.io&charset=%28detect+automatically%29&doctype=Inline&group=0

![image](https://user-images.githubusercontent.com/5632966/82385515-853fb600-99ef-11ea-92bc-df5bab348b69.png)

 install the RapidSSL intermediate Certificate [Download here](https://ssltools.digicert.com/chainTester/webservice/validatecerts/certificate?certKey=issuer.intermediate.cert.94&fileName=RapidSSL%20RSA%20CA%202018&fileExtension=txt)

**Comment by xavier506** [comment]
INSTALLATION INSTRUCTIONS

1. INSTALL CERTIFICATE:
Install the X.509 version of your certificate included at the end of this e-mail.
For installation instructions for your SSL Certificate, go to:
https://knowledge.rapidssl.com/support/ssl-certificate-support/index?page=content&id=INFO2699

2. INTERMEDIATE CERTIFICATE ADVISORY:
You MUST install the RapidSSL intermediate Certificate on your server together with your Certificate or it may not operate correctly.

** MICROSOFT IIS and TOMCAT USERS
Microsoft and Tomcat users are advised to download a PKCS #7 formatted certificate from the GeoTrust User Portal:
https://products.geotrust.com/orders/orderinformation/authentication.do. PKCS #7 is the default format used by these vendors during installation and includes the intermediate CA certificate.

You can get your RapidSSL Intermediate Certificates at:
https://knowledge.rapidssl.com/support/ssl-certificate-support/index?page=content&id=INFO1548

3. CHECK INSTALLATION:
Ensure you have installed your certificate correctly at:
https://knowledge.rapidssl.com/support/ssl-certificate-support/index?page=content&id=SO9556

4. INSTALL THE RAPIDSSL SITE SEAL:
Additionally, as part of your SSL Certificate Service, you are entitled to display the RapidSSL Site Seal - recognized across the Internet and around the world as a symbol of authenticity, security, and trust - to build consumer confidence in your Web site.

Installation instructions for the RapidSSL Site Seal can be found on the following link:
https://knowledge.rapidssl.com/support/ssl-certificate-support/index?page=content&id=SO14424&actp=LIST&viewlocale=en_US

If you require additional technical support please contact your Reseller.

**Comment by kuronosec** [comment]
@xavier506  ups I missed the concatenation step, this is fixed now.
