### ISSUE TITLE
Update CI/CD Config. Use CircleCI

### ISSUE THREAD

**Issue by gaboesquivel** [eoscostarica/eos-rate#44]
Use Circle CI

related to https://github.com/eoscostarica/eos-local/issues/26

**Comment by JulianAlvarado** [comment]
@xavier506 Tenemos visibilidad de donde vamos a hostiar eosrate? Nos comenta Gabo y Kriss que ya podemos actualizar la config de CI/CD y es un buen momento para ir definiendo hosting.

**Comment by kriskoin** [comment]
> @kriskoin vos tenes algun progreso alrededor de este issue?

@JulianAlvarado , aun no,pero se habia mencionado que no es 100% requerido es mas un "nice to have"
