### ISSUE TITLE
List user's ratings with option to remove rating in user profile page.

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/eos-rate#445]
Users may want to clear their rating and recover the ram they paid for , this can be done in a table that lists the user's ratings and a button that clears the rating for each BP. 

The smart contract acton is ready all we nee is the UI design .

**Comment by murillojorge** [comment]
Check this out: https://zpl.io/2GJ36g3

![Desktop Profile](https://user-images.githubusercontent.com/1179619/83708659-04311300-a5da-11ea-8c60-6cba494b5805.png)
