### ISSUE TITLE
Minification breaking session persistence through UAL

### ISSUE THREAD

**Issue by aaroncox** [eoscostarica/eos-rate#448]
So I dug into why persistence is broken with both Scatter and Anchor, and discovered it's actually the minification that's occurring on ual and the ual-reactjs-renderer.

This is only happening in the production build and not within the local development mode. 

You can see this happening if you look on eosrate.io and look in the local storage at the value of `UALLoggedInAuthType`. Currently it's reporting a value of `n`, but should be the name of the authenticator that the user logged in with. If you view the same value in the development mode you'll notice the value is either `Anchor`, `Scatter` or `Ledger`. 

The ual-reactjs-renderer uses the value of `authenticator.constructor.name` which is minified in the react-scripts build process. You can see where the renderer does this here:

https://github.com/EOSIO/ual-reactjs-renderer/blob/0eaaf1ee9b7f941c92a12ee212e8bdcb8621e674/src/components/provider/UALProvider.js#L170

There are two solutions as far as I'm aware: 

1. Modify the build process of eos-rate to prevent the UAL components from being mangled. This would fix the problem immediately, but would increase the filesize of the application. 
2. UAL and the reactjs renderer would need to be updated to provide a better source of authenticator names. I've opened an issue related to this https://github.com/EOSIO/ual-reactjs-renderer/issues/92

**Comment by aaroncox** [comment]
Give `ual-reactjs-renderer@0.3.1` a spin and see if that fixes the issue 👍

**Comment by xavier506** [comment]
@aaroncox  thanks for the heads up ! 

@tetogomez  please update `ual-reactjs-renderer` so we can test it out

**Comment by xavier506** [comment]
@aaroncox  looks like the update did the trick, thanks for your help.
