### ISSUE TITLE
Lynx Integration

### ISSUE THREAD

**Issue by gaboesquivel** [eoscostarica/eos-rate#47]
Docs
https://developers.eoslynx.com/

Telegram
https://t.me/lynxapps

As first step make sure you can read the account name from the wallet API.

**Comment by gaboesquivel** [comment]
Use ScatterJS for this integration [GetScatter/scatter-js#supported-wallets](https://github.com/GetScatter/scatter-js#supported-wallets) 

this is related to https://github.com/eoscostarica/eos-dapp-boilerplate/issues/9

**Comment by jebuscraisp** [comment]
I see there is a plugin  `scatterjs-plugin-lynx` to enable lynx through scatter, is this part of the path ?

https://github.com/GetScatter/scatter-js#plugin-supported-wallets

**Comment by jimenezfer** [comment]
I see there is a plugin `scatterjs-plugin-lynx`, is this part of the path?

https://github.com/GetScatter/scatter-js#plugin-supported-wallets

**Comment by gaboesquivel** [comment]
Yes, correct

**Comment by JulianAlvarado** [comment]
Closing this as we are no longer proceeding with this integration.
