### ISSUE TITLE
My vote info

### ISSUE THREAD

**Issue by murillojorge** [eoscostarica/eos-rate#498]
As a user I want to be able to see my votes and tx links so I can see the values and be able to update them.

![image](https://user-images.githubusercontent.com/5632966/108381318-4ed8d680-71cd-11eb-9769-9d83076a1c9e.png)

**Comment by xavier506** [comment]
Jorge can we update this in a wireframe

**Comment by murillojorge** [comment]
How about this?
https://zpl.io/awzLGYJ

![Your Rating - Desktop](https://user-images.githubusercontent.com/1179619/125849572-7f1e40c3-b01a-4ce8-b719-a7fc3e46e121.png)
