### ISSUE TITLE
Link TX result to block explorer

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/eos-rate#501]
Once I have a successful transaction I want to link to the bloc explorer so I can verify my transaction

**Comment by JustinCast** [comment]
@xavier506 would you extend a little bit on this?

**Comment by xavier506** [comment]
@JustinCast 

> @xavier506 would you extend a little bit on this?

Sure once a transaction is executed we show a success message in the snackbar with a link to the transaction a a block explorer

`REACT_APP_BLOCK_EXPLORER=https://jungle3.bloks.io/transaction/{transaction}`

**Comment by JustinCast** [comment]
> @JustinCast
> 
> > @xavier506 would you extend a little bit on this?
> 
> Sure once a transaction is executed we show a success message in the snackbar with a link to the transaction a a block explorer
> 
> ![image](https://user-images.githubusercontent.com/5632966/115486470-f4331980-a213-11eb-83ed-a0e76acbd0cc.png)
> 
> The success message should include a transaction ID as a hyperlink to a block explorer such as
> 
> **Success! Transaction ID:** [da299...b6857](https://bloks.io/transaction/da299c91d69713b61a59416edf20caaed8c735eb46d9d1639fd31930a74b6857)
> 
> `REACT_APP_BLOCK_EXPLORER=https://jungle3.bloks.io/transaction/{transaction}`

Cool, thank. you.
