### ISSUE TITLE
Sync Staging with Master

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/eos-rate#526]
There seems to be changes in `master` branch that can be manually cherry picked and included into `staging` branch 

here is a diff in an old PR

https://github.com/eoscostarica/eos-rate/pull/521/files

**Comment by JustinCast** [comment]
@kuronosec is there any problem if we do what @xavier506 is proposing?

**Comment by xavier506** [comment]
I think we may need to select which changes are needed since some changes will definitely need to be left out

**Comment by kuronosec** [comment]
@xavier506 @JustinCast hmm strange, the only difference I see right now is the last Justin's PR.
