### ISSUE TITLE
New ratings not updating results

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/eos-rate#537]
When I create a new rating I do not see the results change on the UI

**Comment by kriskoin** [comment]
Should i check the math logic ?

**Comment by xavier506** [comment]
i think it would be good to manually test and see where the problem is , i believe the smart contract executes the transaction but the database is not updated and therefore the ui is not updated either

**Comment by xavier506** [comment]
this is related to #596 

perhaps there is a more elegant way to solve this by re instating Demux 

There can be an action listener that triggers an update in our DB every time a rating occurs
