### ISSUE TITLE
Error appears when clean BP voting selection

### ISSUE THREAD

**Issue by JustinCast** [eoscostarica/eos-rate#548]

**Comment by JustinCast** [comment]
![Uploading image.png…]()

**Comment by leisterfrancisco** [comment]
There are several warning but none of them according one referred here, general console errors will be fixed in https://github.com/eoscostarica/eos-rate/issues/629

**Comment by leisterfrancisco** [comment]
There are several warning but none of them according one referred here, general console errors will be fixed in #629
