### ISSUE TITLE
Serve Block Producer List

### ISSUE THREAD

**Issue by gaboesquivel** [eoscostarica/eos-rate#6]
We need to serve a list of block producers to app containing relevant info from their profile.

Use info from eosio.system with:
Information from the producerjson contract.

**Comment by gaboesquivel** [comment]
Ref https://developers.eos.io/eosio-nodeos/reference . see get_producers

**Comment by gaboesquivel** [comment]
Ref bp.json standard https://github.com/eosrio/bp-info-standard

**Comment by gaboesquivel** [comment]
@murillojorge @rubenabix the idea is to aggregate all data to display, logo, location and all info we can gather from a BP on their profile page

**Comment by gaboesquivel** [comment]
@rubenabix usage example of EOS Camel API pkg https://github.com/gaboesquivel/eos-actions/blob/master/index.js

**Comment by gaboesquivel** [comment]
Another option re-enabling a unix cron we use to have to generate that list on one of EOS Costa Rica nodes monitor.eosio.cr/mainnet-producers.json .. It's not currently working.  Thoughts @xavier506 ?

**Comment by gaboesquivel** [comment]
Actually I think we don't want to be running a node on Zeit just to able to execute cleos to get the system producerslist

**Comment by gaboesquivel** [comment]
I'd look this 

```js
const got = require('got')
const producersList = await got('https://monitor.eosio.cr/mainnet-producers.json')
const getBpJson = (url) => got(url)
const producersData = procudersList.map(bp => getBpJson(bp.bpJsonUrl))
// and finally save the data to MongoDB using the Block Producer mongoose Model
```

**Comment by gaboesquivel** [comment]
I just talked to @xavier506, we are going re-enable the mainent producers json cron job / service and we'll query that.  

No need to run an EOS node on this project. @rubenabix

**Comment by xavier506** [comment]
Para el mainnet-producers.json estoy corriendo el siguiente cron job en el server 
`docker exec eosio /opt/eosio/bin/cleos -u https://api.eosio.cr --wallet-url http://127.0.0.1:8888 system listproducers -l 1000 -j > /var/www/monitor.eosio.cr/public_html/mainnet-producers.json`

**Comment by gaboesquivel** [comment]
Cool, please let us know when we can start using it.

**Comment by xavier506** [comment]
Here is an initial list of BPs in JSON format 

https://github.com/eoscostarica/rate.eoscostarica.io/blob/master/mainnet-producers.json

**Comment by gaboesquivel** [comment]
hey @rubenabix we should be using the On-Chain Data instead.

https://validate.eosnation.io/data/

here you get all BPJSON data from Blockchain. 
https://validate.eosnation.io/bps.json .

**Comment by gaboesquivel** [comment]
I think we can just configure demux to listen to `eosio.system:regblockproducer` and `producerjson_contract:set` 

https://github.com/EOSIO/eos/blob/master/contracts/eosio.system/eosio.system.cpp 

https://github.com/greymass/producerjson/blob/master/producerjson.cpp

**Comment by gaboesquivel** [comment]
solved by https://github.com/eoscostarica/eos-rate/commit/4838b60dc652714d1c6b911ea5a7a31e6428cea9
