### ISSUE TITLE
UI: Block Producer Profile Page

### ISSUE THREAD

**Issue by gaboesquivel** [eoscostarica/eos-rate#60]
![bp-profile](https://user-images.githubusercontent.com/391270/47851727-23811200-dd9f-11e8-85c0-3a4a5152b39f.png)

I think we can start with the following information:

```
General Information

Location:  Costa Rica
Website:  eoscostarica.io 
Position:  #15
Votes:  1.56 %

Economy

Balance: 4.0800 EOS
Staked: 6.7800 EOS
Daily Reward:	500 EOS

Ratings  

Rate: 8.5 
Raters: 450 accounts
```

**Comment by xavier506** [comment]
@JoseBoga  Any updates on how this is coming along? let us know if there is anything we can do to  help

**Comment by JoseBoga** [comment]
@xavier506 I have a issue, but i'll be free tomorrow so i have more time to can fix it
