### ISSUE TITLE
Update EOS Rate and EOS Costa Rica logo, it is not clear

### ISSUE THREAD

**Issue by leisterfrancisco** [eoscostarica/eos-rate#605]
Both logos with its respective contracts doesn't look clear

**Comment by murillojorge** [comment]
Let's replace the logo for this one: https://zpl.io/aMx44XK
Please go ahead and check that all sized and margins are correct. Go into Figma if needed: https://www.figma.com/file/rddpyVTgn2iN6Ow3p0F9kx/?node-id=60283%3A4612
@AngeloCG97
