### ISSUE TITLE
UI: Rate Producer Flow & Assets

### ISSUE THREAD

**Issue by gaboesquivel** [eoscostarica/eos-rate#61]
@murillojorge we need screens for the Rating process from within the BP Profile Page #35

**Comment by murillojorge** [comment]
I'm on it.

**Comment by murillojorge** [comment]
Added to Zeplin.

![desktop bp compare](https://user-images.githubusercontent.com/1179619/48035491-d350d980-e129-11e8-8972-bdd487d7c0c3.png)

**Comment by gaboesquivel** [comment]
thanks
