### ISSUE TITLE
Translate HOC is deprecated

### ISSUE THREAD

**Issue by mahcr** [eoscostarica/eos-rate#64]
Update i18 `translate` HOC and replate with `withNamespace`. 

References:
https://react.i18next.com/deprecated/translate-hoc

Project warning:
<img width="938" alt="screen shot 2018-11-03 at 6 53 13 pm" src="https://user-images.githubusercontent.com/16544451/47958857-d87f1e80-df99-11e8-9d79-583dd27cb780.png">

**Comment by gaboesquivel** [comment]
fixed
