### ISSUE TITLE
Redux HOC error

### ISSUE THREAD

**Issue by mahcr** [eoscostarica/eos-rate#66]
There is an odd error related to the redux HOC

Steps to reproduce:

1. Open http://localhost:3000/block-producers
2. Open the side menu and click on the home button
3. Check the logs. 

<img width="1278" alt="screen shot 2018-11-03 at 7 43 38 pm" src="https://user-images.githubusercontent.com/16544451/47959088-28adaf00-dfa1-11e8-9407-aa166a5ef79c.png">

**Comment by gaboesquivel** [comment]
this might not be necessary with #17

**Comment by gaboesquivel** [comment]
Solved
