### ISSUE TITLE
Inconsistencies in cards

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/eos-rate#665]
Inconsistencies in text font sizes and in position of average rating
## Mainnet
![image](https://user-images.githubusercontent.com/5632966/128576581-1fa385b0-7283-4772-84ba-5f2ca12175fe.png)

## Jungle
![image](https://user-images.githubusercontent.com/5632966/128576598-d14ce74d-72a0-43c1-b103-e53269560d0d.png)

**Comment by AngeloCG97** [comment]
The official is the last screenshot by jorge recommendation
