### ISSUE TITLE
Canceling a rating

### ISSUE THREAD

**Issue by murillojorge** [eoscostarica/eos-rate#702]
When instead of publishing my rating I cancel it, I get a "This BP does not exist" message.
Firefox 91 on MacOS Big Sur.

<img width="404" alt="Screen Shot 2021-08-25 at 21 17 20" src="https://user-images.githubusercontent.com/1179619/130895004-56bd51f9-b70e-4769-b62f-745b50122841.png">

**Comment by xavier506** [comment]
@AngeloCG97  I tried to remove a rating, the tx says `success` but the rating is still visible
