### ISSUE TITLE
Add Footer

### ISSUE THREAD

**Issue by gaboesquivel** [eoscostarica/eos-rate#71]
<img width="469" alt="eos costa rica zeplin scene 2018-11-04 13-04-38" src="https://user-images.githubusercontent.com/391270/47968618-55f66d80-e032-11e8-9a9b-1e127eaf6753.png">

**Comment by danazkari** [comment]
@gaboesquivel / @murillojorge 

Ocupo saber más de qué es lo que se quiere con este bottom app bar? Qué pasa con los botones? Uno es para compartir y el otro para enviar? No sería eso básicamente lo mismo?

Qué debería pasar cuando uno le da compartir? Cómo se debería ver esta barra en un dispositivo móvil? Debería verse en primer lugar?

**Comment by gaboesquivel** [comment]
@danazkari  open our telegram channel, the other sharing icon I think is for position only. We definitively want an icon link to the github repo.

**Comment by xavier506** [comment]
Also we should add some extra padding around the footer so that it doesn't interfere with content.

<img width="1906" alt="screen shot 2018-11-13 at 11 07 20 pm" src="https://user-images.githubusercontent.com/5632966/48487438-ddd33900-e7e3-11e8-852c-b8431c080f62.png">

**Comment by murillojorge** [comment]
We also need the footer not to be fixed, but at the bottom of the main div.

**Comment by xavier506** [comment]
@danazkari can this ticket be closed? seems to be in the `done` bin if the kanban board

**Comment by gaboesquivel** [comment]
done
