### ISSUE TITLE
Update ratings button

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/eos-rate#718]
As a user that is logged in and has already rated a BP the button label should read `Update rating` rather that `Publish Ratings`

![image](https://user-images.githubusercontent.com/5632966/131164800-8015087d-2412-4eee-b6e6-34ee52517eed.png)

![image](https://user-images.githubusercontent.com/5632966/131164893-67497869-ad70-4cb8-95d7-2b2e9748104a.png)

**Comment by xavier506** [comment]
@AngeloCG97  the button on the BP profile page still says rate BP instead of `Update Rating`

![image](https://user-images.githubusercontent.com/5632966/132402735-c41b2024-099d-4d53-aacd-023ebd3667f8.png)

**Comment by xavier506** [comment]
@AngeloCG97 re-opening this issue , the button label still reads "Rate" for BPs i have already reated 

![image](https://user-images.githubusercontent.com/5632966/132776003-79b4f55a-5a85-4d9d-94d1-68f30d3a8470.png)


I want it to say "Update Rating"

**Comment by AngeloCG97** [comment]
Si sorry, I change on rate page but I Don't change on profile page, I worked on this
