### ISSUE TITLE
Add icon for eden member

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/eos-rate#721]
if a user logs in with an eden full member account lets show an icon to show this

![image](https://user-images.githubusercontent.com/5632966/131182114-de3b136a-ba52-47b8-9bd9-c81ac6b2d526.png)

**Comment by xavier506** [comment]
can be the same lock icon

**Comment by murillojorge** [comment]
Take a look at this option: https://zpl.io/aMx44XK
Eden icon: https://zpl.io/bloNNXv
@xavier506 @AngeloCG97

**Comment by xavier506** [comment]
@AngeloCG97  Eden Logo dos not appear for eden members

![image](https://user-images.githubusercontent.com/5632966/132414112-3440cb27-0981-4d8c-aa89-8c738d522224.png)
