### ISSUE TITLE
Removal of Eden Member Requirement to vote/proxy to use the eosrate.io tool

### ISSUE THREAD

**Issue by ChrisBarnes79** [eoscostarica/eos-rate#723]
**Is your feature request related to a problem? Please describe.**
Hi Guys, in follow up to our discussion last week, I've gone to eosrate.io and tried to rate a BP with my Eden account and see that I can't bc I'm not voting or proxying with it. As mentioned many Eden members use "shell" EOS accounts for their Eden membership and therefore may not be doing any staking and therefore won't have any staked tokens to vote with or would even bother considering they have so few tokens in their Eden account.

**Describe the solution you'd like**
Would you be able to whitelist the Eden on EOS accounts from this requirement so they can rate BPs without having voted nor proxied from that account?

**Describe alternatives you've considered**
I'm not sure what else could be done to resolve this other than just making an exception for active Eden member accounts. For other, non-Eden accounts, I think this makes a lot of sense to have as a criteria, but for this instance it shouldn't be necessary.

I will likely hold off on pushing the eosrate.io tool to Eden members until this bit gets resolved as I don't want to lose their attention by attempting to rate a BP and getting an error. So ideally this can be done soon so I can then push this out.

Thanks for the help as always!
Chris

**Comment by leisterfrancisco** [comment]
@ChrisBarnes79 thank you very much for your feedback, the task you request is already implemented

**Comment by ChrisBarnes79** [comment]
Awesome!! You guys are fast :) This is my first interaction with Github, and its pretty cool! Thanks for having this set up and pointing me to it :)
