### ISSUE TITLE
Testnet logo

### ISSUE THREAD

**Issue by murillojorge** [eoscostarica/eos-rate#735]
Let's use this logo for the testnet site: https://zpl.io/2jdl8px
Refer to this frame: https://zpl.io/a8qWZWE

**Comment by xavier506** [comment]
@AngeloCG97  the mainnet logo version is showing `testnet` 

![image](https://user-images.githubusercontent.com/5632966/132402975-f93c3663-db44-4af6-840c-ad750ccabdeb.png)
