### ISSUE TITLE
can call `rmrate` even though rating has already been deleted

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/eos-rate#747]
i should validate the rating exists before deleting it

![image](https://user-images.githubusercontent.com/5632966/132101430-b0ea18dd-5d70-450b-a1be-c4bba53f8310.png)

**Comment by leisterfrancisco** [comment]
@xavier506 you mean, add a `check`? because already exist that validation, take a look at [here](https://github.com/eoscostarica/eos-rate/blob/staging/contracts/rateproducer/src/rateproducer.cpp#L457)
