### ISSUE TITLE
Radar styling 

### ISSUE THREAD

**Issue by murillojorge** [eoscostarica/eos-rate#76]
We need to style the radars so they all look the same and according to the design. 
Please refer to: https://zpl.io/bPvGEL6
If you do not have access to the Zeplin project contact me.

![radar prototype blank](https://user-images.githubusercontent.com/1179619/48383794-eb39d780-e6ac-11e8-9f11-a6f02f41608e.png)

**Comment by xavier506** [comment]
hello @murillojorge  please add my user `xavier@eoscostarica.io` to the Zeppelin project

**Comment by cristian-ramirez** [comment]
Hi @murillojorge please add me; ramireze4@gmail.com

**Comment by murillojorge** [comment]
Both added to Zeplin.

**Comment by gaboesquivel** [comment]
solved by https://github.com/eoscostarica/eos-rate/pull/81
