### ISSUE TITLE
Separate designs per release

### ISSUE THREAD

**Issue by gaboesquivel** [eoscostarica/eos-rate#79]
We need to separate the designs into releases based on the Roadmap https://github.com/eoscostarica/eos-rate#feature-roadmap

**Comment by murillojorge** [comment]
A new set of v1.0 prototypes can be found on Zeplin.

**Comment by gaboesquivel** [comment]
thanks perfect, 

here https://scene.zeplin.io/project/5a58ea3341f76658994e000c
