### ISSUE TITLE
My rating is not showing

### ISSUE THREAD

**Issue by murillojorge** [eoscostarica/eos-rate#832]
I just rated a Bp but my values are not showing on the radar or the table.
Firefox 92.0.1, Anchor 1.2.9, on MacOS Big Sur.
<img width="1337" alt="Screen Shot 2021-10-11 at 21 19 26" src="https://user-images.githubusercontent.com/1179619/136885776-42fd8bec-6a84-4cb7-95e0-0e96d1fec352.png">

**Comment by tetogomez** [comment]
Note: 
Change label name
General Rating -> EOS Rating

Enable total and my rating
disable EOS and general (ratings)

@AngeloCG97
