### ISSUE TITLE
Snackbar message is not clear

### ISSUE THREAD

**Issue by murillojorge** [eoscostarica/eos-rate#833]
Let's use a more humane message.
"Rating complete. Transaction: c7743505"

<img width="1331" alt="Screen Shot 2021-10-11 at 21 22 19" src="https://user-images.githubusercontent.com/1179619/136886128-b02578b5-05c9-4784-a214-d3dc3c5121e1.png">

**Comment by tetogomez** [comment]
"Transaction completed: [c7743505](blocks.io)"
