### ISSUE TITLE
Improve BP Profile page link

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/eos-rate#98]
The area that servers as a link for the BP profile page is reduced to only the icon which is not very intuitive. Maybe the entire card header could be made a link? 

Perhaps tooltips could help guide users to "click to view BP profile"

<img width="387" alt="screen shot 2018-11-23 at 10 17 51 pm" src="https://user-images.githubusercontent.com/5632966/48964486-07bbf680-ef6e-11e8-813b-ec0f91949a32.png">

**Comment by gaboesquivel** [comment]
on the footer:
![Alt text](https://monosnap.com/image/5Nu7uZwWgdC0w0mzbRtutwquwHwibe.png)

remove person icon, and leave + on the left hand side and info icon with link on the right hand side.

Make all the header clickable / tappable and link to the bp profile

**Comment by xavier506** [comment]
The info icon is a link to the BP's website, I am thinking there is probably a better icon for depicting a website , for example :
<img width="566" alt="screen shot 2018-12-08 at 11 10 19 am" src="https://user-images.githubusercontent.com/5632966/49686880-df89d700-fad9-11e8-979d-b115d137f8a4.png">

I am not sure if it is possible to add some hover text (aka tooltips) to some of these icons , for example:
`Add BP to compare`
`Visit Website`
`View BP profile`
