### ISSUE TITLE
Block Producer Card Icons

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/eos-rate#99]
Lets' look around for some great icons for the three categories on the BP profile cards. My suggestion is we propose different icons and decide on which icons represent best what each link is about .

Tooltips can also be helpful to describe each link without cluttering the design with text.

<img width="340" alt="screen shot 2018-11-24 at 1 07 21 am" src="https://user-images.githubusercontent.com/5632966/48965601-f5e64d80-ef85-11e8-82e7-8a9f2e33d896.png">

- Add BP to compare 
- Visit Website
- View BP profile

**Comment by gaboesquivel** [comment]
close in favor of #98
